[advisories]
unmaintained = "workspace"

[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "GPL-3.0-or-later",
    "ISC",
    "MIT",
    "MPL-2.0",
    "OFL-1.1",
    "Unicode-3.0",
    "Ubuntu-font-1.0",
    "Zlib",
]

[bans]
multiple-versions = "allow"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
